
### export  vars and alias
#for WSL installation
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

# alias for kubectl
alias ksc='kubectl config set-context $(kubectl config current-context) --namespace '
alias k=kubectl
alias kconget='kubectl config get-contexts'
alias kconuse='kubectl config use-context '

# bash-completion must be install first: apt-get install bash-completion
source <(kubectl completion bash)

# alias for pulumi
alias pu='pulumi'

#aws eks alias
alias awsls='aws eks list-clusters'
alias awskonf='aws eks update-kubeconfig --name'

if [[ $(type -t compopt) = "builtin" ]]; then
    complete -o default -F __start_kubectl k
else
    complete -o default -o nospace -F __start_kubectl k
fi


# add Pulumi to the PATH
export PATH=$PATH:$HOME/.pulumi/bin

#Golang stuff
export PATH=$PATH:/usr/local/go/bin
export GOPATH="$(go env GOPATH)"
export PATH="${PATH}:${GOPATH}/bin"