#!/usr/bin/env python3
import sys
import os


# MAIN
def main():
    if len(sys.argv) > 2:
        match sys.argv[2]:
            case "one":
                print(sys.argv[1])
            case "two":
                print(sys.argv[2])
    else:
        print("ERROR | not enough arguments to run: check args")
        os._exit(0)

if __name__== "__main__":
    sys.exit(main())

